//! Generated by scripts/dev/regenerate_integration_test_root.py. Do not edit by hand.

// Force Cargo to rebuild SQLx migration macros when their directory changes.
const _: &str = env!("FJCLOUD_MIGRATIONS_FINGERPRINT");

mod common;

#[path = "integration/admin_alerts_test.rs"]
mod admin_alerts_test;
#[path = "integration/admin_audit_view_test.rs"]
mod admin_audit_view_test;
#[path = "integration/admin_broadcast_test.rs"]
mod admin_broadcast_test;
#[path = "integration/admin_cold_test.rs"]
mod admin_cold_test;
#[path = "integration/admin_deployments_test.rs"]
mod admin_deployments_test;
#[path = "integration/admin_migrations_test.rs"]
mod admin_migrations_test;
#[path = "integration/admin_providers_test.rs"]
mod admin_providers_test;
#[path = "integration/admin_token_audit_test.rs"]
mod admin_token_audit_test;
#[path = "integration/admin_vm_host_metrics_test.rs"]
mod admin_vm_host_metrics_test;
#[path = "integration/admin_vm_kill_test.rs"]
mod admin_vm_kill_test;
#[path = "integration/admin_vms_test.rs"]
mod admin_vms_test;
#[path = "integration/admin_webhook_events_test.rs"]
mod admin_webhook_events_test;
#[path = "integration/api_key_auth_test.rs"]
mod api_key_auth_test;
#[path = "integration/auth_endpoints_test.rs"]
mod auth_endpoints_test;
#[path = "integration/auth_lockout_test.rs"]
mod auth_lockout_test;
#[path = "integration/auth_test.rs"]
mod auth_test;
#[path = "integration/flapjack_proxy_security_sources_test.rs"]
mod flapjack_proxy_security_sources_test;
#[path = "integration/garage_admin_client_test.rs"]
mod garage_admin_client_test;
#[path = "integration/internal_auth_test.rs"]
mod internal_auth_test;
#[path = "integration/migration_048_oauth_identities_test.rs"]
mod migration_048_oauth_identities_test;
#[path = "integration/migration_052_auth_lockout_state_test.rs"]
mod migration_052_auth_lockout_state_test;
#[path = "integration/oauth_start_routes_test.rs"]
mod oauth_start_routes_test;
#[path = "integration/reliability_security_test.rs"]
mod reliability_security_test;
#[path = "integration/security_test.rs"]
mod security_test;
#[path = "integration/storage_s3_auth_test.rs"]
mod storage_s3_auth_test;
