//! Generated by scripts/dev/regenerate_integration_test_root.py. Do not edit by hand.

// Force Cargo to rebuild SQLx migration macros when their directory changes.
const _: &str = env!("FJCLOUD_MIGRATIONS_FINGERPRINT");

mod common;

#[path = "integration/billing_endpoints_test.rs"]
mod billing_endpoints_test;
#[path = "integration/billing_estimate_test.rs"]
mod billing_estimate_test;
#[path = "integration/billing_regression_test.rs"]
mod billing_regression_test;
#[path = "integration/cross_region_billing_test.rs"]
mod cross_region_billing_test;
#[path = "integration/integration_stripe_test.rs"]
mod integration_stripe_test;
#[path = "integration/invoice_email_test.rs"]
mod invoice_email_test;
#[path = "integration/invoices_test.rs"]
mod invoices_test;
#[path = "integration/quota_enforcement_test.rs"]
mod quota_enforcement_test;
#[path = "integration/stripe_billing_test.rs"]
mod stripe_billing_test;
#[path = "integration/stripe_local_dispatch_test.rs"]
mod stripe_local_dispatch_test;
#[path = "integration/stripe_pay_invoice_test.rs"]
mod stripe_pay_invoice_test;
#[path = "integration/stripe_test_clock_full_cycle_test.rs"]
mod stripe_test_clock_full_cycle_test;
#[path = "integration/stripe_webhook_event_matrix_test.rs"]
mod stripe_webhook_event_matrix_test;
#[path = "integration/stripe_webhook_idempotency_test.rs"]
mod stripe_webhook_idempotency_test;
#[path = "integration/stripe_webhook_signature_test.rs"]
mod stripe_webhook_signature_test;
#[path = "integration/usage_test.rs"]
mod usage_test;
