//! Generated by scripts/dev/regenerate_integration_test_root.py. Do not edit by hand.

mod common;

#[path = "integration/admin_indexes_test.rs"]
mod admin_indexes_test;
#[path = "integration/admin_replicas_test.rs"]
mod admin_replicas_test;
#[path = "integration/discovery_test.rs"]
mod discovery_test;
#[path = "integration/flapjack_proxy_analytics_experiments_debug_test.rs"]
mod flapjack_proxy_analytics_experiments_debug_test;
#[path = "integration/index_metrics_scrape_test.rs"]
mod index_metrics_scrape_test;
#[path = "integration/index_replica_repo_test.rs"]
mod index_replica_repo_test;
#[path = "integration/indexes_ai_routes_test.rs"]
mod indexes_ai_routes_test;
#[path = "integration/indexes_security_sources_routes_test.rs"]
mod indexes_security_sources_routes_test;
#[path = "integration/indexes_test.rs"]
mod indexes_test;
#[path = "integration/pg_index_replica_repo_test.rs"]
mod pg_index_replica_repo_test;
#[path = "integration/reliability_replication_test.rs"]
mod reliability_replication_test;
#[path = "integration/replication_test.rs"]
mod replication_test;
#[path = "integration/restore_endpoints_test.rs"]
mod restore_endpoints_test;
#[path = "integration/restore_job_repo_test.rs"]
mod restore_job_repo_test;
