//! Generated by scripts/dev/regenerate_integration_test_root.py. Do not edit by hand.

mod common;

#[path = "integration/access_tracker_test.rs"]
mod access_tracker_test;
#[path = "integration/account_test.rs"]
mod account_test;
#[path = "integration/admin_alerts_test.rs"]
mod admin_alerts_test;
#[path = "integration/admin_audit_view_test.rs"]
mod admin_audit_view_test;
#[path = "integration/admin_broadcast_test.rs"]
mod admin_broadcast_test;
#[path = "integration/admin_cold_test.rs"]
mod admin_cold_test;
#[path = "integration/admin_deployments_test.rs"]
mod admin_deployments_test;
#[path = "integration/admin_indexes_test.rs"]
mod admin_indexes_test;
#[path = "integration/admin_migrations_test.rs"]
mod admin_migrations_test;
#[path = "integration/admin_providers_test.rs"]
mod admin_providers_test;
#[path = "integration/admin_replicas_test.rs"]
mod admin_replicas_test;
#[path = "integration/admin_token_audit_test.rs"]
mod admin_token_audit_test;
#[path = "integration/admin_vm_kill_test.rs"]
mod admin_vm_kill_test;
#[path = "integration/admin_vms_test.rs"]
mod admin_vms_test;
#[path = "integration/admin_webhook_events_test.rs"]
mod admin_webhook_events_test;
#[path = "integration/alerting_test.rs"]
mod alerting_test;
#[path = "integration/alerting_webhook_smoke_test.rs"]
mod alerting_webhook_smoke_test;
#[path = "integration/api_key_auth_test.rs"]
mod api_key_auth_test;
#[path = "integration/api_key_endpoints_test.rs"]
mod api_key_endpoints_test;
#[path = "integration/api_key_repo_test.rs"]
mod api_key_repo_test;
#[path = "integration/auth_endpoints_test.rs"]
mod auth_endpoints_test;
#[path = "integration/auth_lockout_test.rs"]
mod auth_lockout_test;
#[path = "integration/auth_test.rs"]
mod auth_test;
#[path = "integration/aws_provisioner_test.rs"]
mod aws_provisioner_test;
#[path = "integration/billing_endpoints_test.rs"]
mod billing_endpoints_test;
#[path = "integration/billing_estimate_test.rs"]
mod billing_estimate_test;
#[path = "integration/billing_regression_test.rs"]
mod billing_regression_test;
#[path = "integration/browser_error_reporting_test.rs"]
mod browser_error_reporting_test;
#[path = "integration/cold_snapshot_repo_test.rs"]
mod cold_snapshot_repo_test;
#[path = "integration/cold_tier_integration_test.rs"]
mod cold_tier_integration_test;
#[path = "integration/cold_tier_test.rs"]
mod cold_tier_test;
#[path = "integration/cross_region_billing_test.rs"]
mod cross_region_billing_test;
#[path = "integration/cross_repo_contract_test.rs"]
mod cross_repo_contract_test;
#[path = "integration/cross_tenant_isolation_test.rs"]
mod cross_tenant_isolation_test;
#[path = "integration/customer_hard_delete_test.rs"]
mod customer_hard_delete_test;
#[path = "integration/deployment_repo_test.rs"]
mod deployment_repo_test;
#[path = "integration/deployments_route_removed_test.rs"]
mod deployments_route_removed_test;
#[path = "integration/deployments_test.rs"]
mod deployments_test;
#[path = "integration/discovery_test.rs"]
mod discovery_test;
#[path = "integration/dns_test.rs"]
mod dns_test;
#[path = "integration/email_service_test.rs"]
mod email_service_test;
#[path = "integration/email_test.rs"]
mod email_test;
#[path = "integration/flapjack_proxy_ai_methods_test.rs"]
mod flapjack_proxy_ai_methods_test;
#[path = "integration/flapjack_proxy_analytics_experiments_debug_test.rs"]
mod flapjack_proxy_analytics_experiments_debug_test;
#[path = "integration/flapjack_proxy_domain_methods_test.rs"]
mod flapjack_proxy_domain_methods_test;
#[path = "integration/flapjack_proxy_migration_test.rs"]
mod flapjack_proxy_migration_test;
#[path = "integration/flapjack_proxy_routing_edge_cases_test.rs"]
mod flapjack_proxy_routing_edge_cases_test;
#[path = "integration/flapjack_proxy_security_sources_test.rs"]
mod flapjack_proxy_security_sources_test;
#[path = "integration/flapjack_proxy_test.rs"]
mod flapjack_proxy_test;
#[path = "integration/free_tier_caps_test.rs"]
mod free_tier_caps_test;
#[path = "integration/garage_admin_client_test.rs"]
mod garage_admin_client_test;
#[path = "integration/garage_object_store_test.rs"]
mod garage_object_store_test;
#[path = "integration/gcp_provisioner_test.rs"]
mod gcp_provisioner_test;
#[path = "integration/ha_demo_integration_test.rs"]
mod ha_demo_integration_test;
#[path = "integration/health_monitor_alert_test.rs"]
mod health_monitor_alert_test;
#[path = "integration/health_monitor_test.rs"]
mod health_monitor_test;
#[path = "integration/health_test.rs"]
mod health_test;
#[path = "integration/heartbeat_publisher_test.rs"]
mod heartbeat_publisher_test;
#[path = "integration/hetzner_provisioner_test.rs"]
mod hetzner_provisioner_test;
#[path = "integration/index_replica_repo_test.rs"]
mod index_replica_repo_test;
#[path = "integration/indexes_ai_routes_test.rs"]
mod indexes_ai_routes_test;
#[path = "integration/indexes_security_sources_routes_test.rs"]
mod indexes_security_sources_routes_test;
#[path = "integration/indexes_test.rs"]
mod indexes_test;
#[path = "integration/input_validation_test.rs"]
mod input_validation_test;
#[path = "integration/integration_cold_tier_test.rs"]
mod integration_cold_tier_test;
#[path = "integration/integration_flapjack_proxy_test.rs"]
mod integration_flapjack_proxy_test;
#[path = "integration/integration_health_monitor_test.rs"]
mod integration_health_monitor_test;
#[path = "integration/integration_metering_pipeline_test.rs"]
mod integration_metering_pipeline_test;
#[path = "integration/integration_metrics_test.rs"]
mod integration_metrics_test;
#[path = "integration/integration_smoke_test.rs"]
mod integration_smoke_test;
#[path = "integration/integration_stripe_test.rs"]
mod integration_stripe_test;
#[path = "integration/internal_auth_test.rs"]
mod internal_auth_test;
#[path = "integration/invoice_email_test.rs"]
mod invoice_email_test;
#[path = "integration/invoices_test.rs"]
mod invoices_test;
#[path = "integration/invoicing_compute_test.rs"]
mod invoicing_compute_test;
#[path = "integration/logging_test.rs"]
mod logging_test;
#[path = "integration/metering_multitenant_test.rs"]
mod metering_multitenant_test;
#[path = "integration/metrics_endpoint_test.rs"]
mod metrics_endpoint_test;
#[path = "integration/migration_046_drops_subscriptions_test.rs"]
mod migration_046_drops_subscriptions_test;
#[path = "integration/migration_048_oauth_identities_test.rs"]
mod migration_048_oauth_identities_test;
#[path = "integration/migration_052_auth_lockout_state_test.rs"]
mod migration_052_auth_lockout_state_test;
#[path = "integration/migration_053_disputes_test.rs"]
mod migration_053_disputes_test;
#[path = "integration/migration_054_password_reset_resend_cooldown_test.rs"]
mod migration_054_password_reset_resend_cooldown_test;
#[path = "integration/migration_routes_test.rs"]
mod migration_routes_test;
#[path = "integration/migration_test.rs"]
mod migration_test;
#[path = "integration/multi_provisioner_test.rs"]
mod multi_provisioner_test;
#[path = "integration/node_secret_test.rs"]
mod node_secret_test;
#[path = "integration/noisy_neighbor_test.rs"]
mod noisy_neighbor_test;
#[path = "integration/oauth_start_routes_test.rs"]
mod oauth_start_routes_test;
#[path = "integration/object_store_test.rs"]
mod object_store_test;
#[path = "integration/oci_provisioner_test.rs"]
mod oci_provisioner_test;
#[path = "integration/onboarding_credentials_test.rs"]
mod onboarding_credentials_test;
#[path = "integration/onboarding_test.rs"]
mod onboarding_test;
#[path = "integration/openapi_spec_final_test.rs"]
mod openapi_spec_final_test;
#[path = "integration/openapi_spec_stages3_5_test.rs"]
mod openapi_spec_stages3_5_test;
#[path = "integration/openapi_spec_test.rs"]
mod openapi_spec_test;
#[path = "integration/pg_customer_repo_schema_harness_test.rs"]
mod pg_customer_repo_schema_harness_test;
#[path = "integration/pg_customer_repo_test.rs"]
mod pg_customer_repo_test;
#[path = "integration/pg_dispute_repo_test.rs"]
mod pg_dispute_repo_test;
#[path = "integration/pg_index_replica_repo_test.rs"]
mod pg_index_replica_repo_test;
#[path = "integration/pg_webhook_event_repo_test.rs"]
mod pg_webhook_event_repo_test;
#[path = "integration/placement_test.rs"]
mod placement_test;
#[path = "integration/pricing_compare_test.rs"]
mod pricing_compare_test;
#[path = "integration/provisioner_test.rs"]
mod provisioner_test;
#[path = "integration/provisioning_service_test.rs"]
mod provisioning_service_test;
#[path = "integration/public_site_test.rs"]
mod public_site_test;
#[path = "integration/quota_enforcement_test.rs"]
mod quota_enforcement_test;
#[path = "integration/rate_card_test.rs"]
mod rate_card_test;
#[path = "integration/region_failover_test.rs"]
mod region_failover_test;
#[path = "integration/reliability_api_crash_test.rs"]
mod reliability_api_crash_test;
#[path = "integration/reliability_cold_tier_test.rs"]
mod reliability_cold_tier_test;
#[path = "integration/reliability_failure_injection_test.rs"]
mod reliability_failure_injection_test;
#[path = "integration/reliability_migration_test.rs"]
mod reliability_migration_test;
#[path = "integration/reliability_profile_freshness_test.rs"]
mod reliability_profile_freshness_test;
#[path = "integration/reliability_replication_test.rs"]
mod reliability_replication_test;
#[path = "integration/reliability_security_test.rs"]
mod reliability_security_test;
#[path = "integration/replica_service_test.rs"]
mod replica_service_test;
#[path = "integration/replication_test.rs"]
mod replication_test;
#[path = "integration/restore_endpoints_test.rs"]
mod restore_endpoints_test;
#[path = "integration/restore_job_repo_test.rs"]
mod restore_job_repo_test;
#[path = "integration/restore_test.rs"]
mod restore_test;
#[path = "integration/scheduler_test.rs"]
mod scheduler_test;
#[path = "integration/security_test.rs"]
mod security_test;
#[path = "integration/ses_bounce_complaint_handler_test.rs"]
mod ses_bounce_complaint_handler_test;
#[path = "integration/signup_abuse_test.rs"]
mod signup_abuse_test;
#[path = "integration/ssh_provisioner_test.rs"]
mod ssh_provisioner_test;
#[path = "integration/storage_bucket_repo_test.rs"]
mod storage_bucket_repo_test;
#[path = "integration/storage_key_repo_test.rs"]
mod storage_key_repo_test;
#[path = "integration/storage_load_test.rs"]
mod storage_load_test;
#[path = "integration/storage_s3_auth_test.rs"]
mod storage_s3_auth_test;
#[path = "integration/storage_s3_bucket_lifecycle_integration_test.rs"]
mod storage_s3_bucket_lifecycle_integration_test;
#[path = "integration/storage_s3_bucket_routes_test.rs"]
mod storage_s3_bucket_routes_test;
#[path = "integration/storage_s3_concurrent_metering_test.rs"]
mod storage_s3_concurrent_metering_test;
#[path = "integration/storage_s3_error_test.rs"]
mod storage_s3_error_test;
#[path = "integration/storage_s3_extractor_test.rs"]
mod storage_s3_extractor_test;
#[path = "integration/storage_s3_integration_test.rs"]
mod storage_s3_integration_test;
#[path = "integration/storage_s3_object_metering_concurrency_test.rs"]
mod storage_s3_object_metering_concurrency_test;
#[path = "integration/storage_s3_object_routes_test.rs"]
mod storage_s3_object_routes_test;
#[path = "integration/storage_s3_proxy_test.rs"]
mod storage_s3_proxy_test;
#[path = "integration/storage_s3_xml_test.rs"]
mod storage_s3_xml_test;
#[path = "integration/storage_service_test.rs"]
mod storage_service_test;
#[path = "integration/stripe_billing_test.rs"]
mod stripe_billing_test;
#[path = "integration/stripe_local_dispatch_test.rs"]
mod stripe_local_dispatch_test;
#[path = "integration/stripe_pay_invoice_test.rs"]
mod stripe_pay_invoice_test;
#[path = "integration/stripe_test_clock_full_cycle_test.rs"]
mod stripe_test_clock_full_cycle_test;
#[path = "integration/stripe_webhook_event_matrix_test.rs"]
mod stripe_webhook_event_matrix_test;
#[path = "integration/stripe_webhook_idempotency_test.rs"]
mod stripe_webhook_idempotency_test;
#[path = "integration/stripe_webhook_signature_test.rs"]
mod stripe_webhook_signature_test;
#[path = "integration/tenant_repo_test.rs"]
mod tenant_repo_test;
#[path = "integration/tenants_test.rs"]
mod tenants_test;
#[path = "integration/usage_test.rs"]
mod usage_test;
#[path = "integration/version_test.rs"]
mod version_test;
#[path = "integration/vm_inventory_test.rs"]
mod vm_inventory_test;
#[path = "integration/webhook_alert_test.rs"]
mod webhook_alert_test;
#[path = "integration/webhook_dunning_email_test.rs"]
mod webhook_dunning_email_test;
#[path = "integration/webhook_lag_publisher_test.rs"]
mod webhook_lag_publisher_test;

#[cfg(feature = "proptest-tests")]
#[path = "integration/tenant_isolation_proptest.rs"]
mod tenant_isolation_proptest;
