#!/usr/bin/env bash
# Web frontend API_BASE_URL contract probe. Verifies that the deployed
# SvelteKit frontend at each environment's cloud.* origin is generating
# OAuth-start hrefs that point at the API origin matching ITS OWN env --
# i.e. staging frontend points at staging API, prod frontend points at prod
# API.
#
# Why: the SvelteKit server load reads $env/dynamic/private.API_BASE_URL
# (see web/src/lib/config.ts::getApiBaseUrl). On Cloudflare Pages this maps
# to the Pages project's "Functions environment variables" set per
# environment in the Pages dashboard (Settings -> Environment variables ->
# Production/Preview). If staging's API_BASE_URL is set to prod's API URL,
# OAuth-start links generated by OAuthButtons.svelte point at prod -- the
# consent flow targets the wrong redirect_uri, the callback comes back to
# prod, and even when the user lands on staging /dashboard the session
# cookie was signed by prod JWT_SECRET so staging's auth guard bounces to
# /login?reason=session_expired.
#
# Anchored: 2026-05-21 fjcloud Lane 4 LB-2 (signup_to_paid_invoice.spec.ts)
# and LB-3 (billing_portal_payment_method_update.spec.ts) failed with this
# exact symptom. Live probe at that time:
#   curl -s https://cloud.staging.flapjack.foo/signup \
#     | grep -oE 'href="[^"]*oauth[^"]*"'
#   -> href="https://api.flapjack.foo/auth/oauth/google/start"   (WRONG)
#   -> href="https://api.flapjack.foo/auth/oauth/github/start"   (WRONG)
#
# Technique: fetch /signup HTML, extract OAuth-start hrefs, assert their
# scheme://host matches the expected API origin for the env. No secrets
# required.
#
# Usage:
#   web_api_base_url_contract.sh [prod|staging|all]
#
# Exit: 0 if all probed envs pass; 1 if any FAIL or hard ERROR; 2 on
# usage error.
set -euo pipefail

env_arg="${1:-all}"
[[ "$env_arg" == "prod" || "$env_arg" == "staging" || "$env_arg" == "all" ]] \
  || { echo "usage: $0 [prod|staging|all]" >&2; exit 2; }

# Per-env web origin and expected API origin. Bash 3.2 portable functions
# (associative arrays would require bash 4+, which macOS does not ship).
web_origin_for() {
  case "$1" in
    prod)    printf '%s' "https://cloud.flapjack.foo" ;;
    staging) printf '%s' "https://cloud.staging.flapjack.foo" ;;
  esac
}
expected_api_origin_for() {
  case "$1" in
    prod)    printf '%s' "https://api.flapjack.foo" ;;
    staging) printf '%s' "https://api.staging.flapjack.foo" ;;
  esac
}

fail=0

probe_env() {
  local env="$1"
  local web_origin expected_api signup_url html oauth_hrefs observed_origin
  web_origin="$(web_origin_for "$env")"
  expected_api="$(expected_api_origin_for "$env")"
  signup_url="${web_origin}/signup"

  # --max-time 15: the worker cold-start on Cloudflare Pages is occasionally
  # slow; 15s leaves headroom without hanging CI.
  html="$(curl -sS --max-time 15 "$signup_url" 2>&1 || true)"
  if [[ -z "$html" ]]; then
    echo "ERROR: env=$env GET $signup_url returned empty body"
    fail=1
    return
  fi

  # grep -oE returns each match on its own line. We expect at least one
  # google or github OAuth-start href; OAuthButtons.svelte renders both.
  oauth_hrefs="$(printf '%s' "$html" | grep -oE 'href="[^"]*/auth/oauth/(google|github)/start"' || true)"
  if [[ -z "$oauth_hrefs" ]]; then
    echo "ERROR: env=$env no OAuth-start hrefs found at $signup_url"
    echo "       The signup page may have changed shape -- inspect web/src/lib/components/OAuthButtons.svelte"
    fail=1
    return
  fi

  # Pull the scheme://host out of each href and dedupe. All hrefs must
  # share the SAME origin AND match the expected API origin.
  observed_origin="$(printf '%s\n' "$oauth_hrefs" \
    | sed -E 's|href="([a-z]+://[^/]+).*|\1|' \
    | sort -u)"

  if [[ "$(printf '%s\n' "$observed_origin" | wc -l | tr -d ' ')" != "1" ]]; then
    echo "FAIL: env=$env OAuth-start hrefs mix multiple origins:"
    printf '       %s\n' $observed_origin
    fail=1
    return
  fi

  if [[ "$observed_origin" != "$expected_api" ]]; then
    echo "FAIL: env=$env web frontend points OAuth-start at WRONG API origin"
    echo "       web frontend: $web_origin"
    echo "       expected API: $expected_api"
    echo "       observed API: $observed_origin"
    echo "       Fix: Cloudflare Pages dashboard -> the Pages project serving"
    echo "            $web_origin -> Settings -> Environment variables ->"
    echo "            the deployment env serving this origin (Production or"
    echo "            Preview, depending on project layout) -> set"
    echo "            API_BASE_URL=$expected_api -> trigger redeploy."
    echo "       Note: the env var is read via \$env/dynamic/private at"
    echo "             runtime (Cloudflare Pages Functions env), NOT a"
    echo "             build-time PUBLIC_* var. See web/src/lib/config.ts."
    fail=1
    return
  fi

  echo "PASS: env=$env $web_origin OAuth-start -> $observed_origin"
}

case "$env_arg" in
  prod)    probe_env prod ;;
  staging) probe_env staging ;;
  all)     probe_env prod; probe_env staging ;;
esac

exit "$fail"
