#!/usr/bin/env bash
# generate_ssm_env.sh — Read SSM parameters and write runtime env files.
#
# Single source of truth for the SSM-param-name -> env-var-name mapping.
# Called on-instance before service restart to populate the EnvironmentFile
# contracts referenced by systemd units:
#   - /etc/fjcloud/env            (fjcloud-api, fjcloud-aggregation-job)
#   - /etc/fjcloud/metering-env   (fj-metering-agent)
#
# Usage: generate_ssm_env.sh <env>
#   env: staging | prod
#
# Requires: aws CLI with IAM role that can ssm:GetParametersByPath + kms:Decrypt.

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: generate_ssm_env.sh <env>"
  exit 1
fi

ENV="$1"
REGION="${AWS_DEFAULT_REGION:-us-east-1}"
SSM_PREFIX="/fjcloud/${ENV}"
ENV_FILE="/etc/fjcloud/env"
METERING_ENV_FILE="/etc/fjcloud/metering-env"

if [[ "$ENV" != "staging" && "$ENV" != "prod" ]]; then
  echo "ERROR: env must be 'staging' or 'prod' (got: ${ENV})"
  exit 1
fi

# ---------------------------------------------------------------------------
# SSM param name -> env var name mapping
#
# Keys are the SSM parameter suffix (after /fjcloud/<env>/).
# Values are the env var names that infra/api/src/config.rs::from_reader and
# infra/api/src/startup_env.rs::StartupEnvSnapshot expect.
#
# Parameters NOT in this map are skipped (e.g., last_deploy_sha, db_password).
# ---------------------------------------------------------------------------

declare -A SSM_TO_ENV=(
  # Required by config.rs::from_reader
  [database_url]="DATABASE_URL"
  [jwt_secret]="JWT_SECRET"
  [admin_key]="ADMIN_KEY"

  # Shared-VM provisioning — infra/api/src/provisioner/aws.rs
  [aws_ami_id]="AWS_AMI_ID"
  [aws_subnet_id]="AWS_SUBNET_ID"
  [aws_security_group_ids]="AWS_SECURITY_GROUP_IDS"
  [aws_key_pair_name]="AWS_KEY_PAIR_NAME"
  [aws_instance_profile_name]="AWS_INSTANCE_PROFILE_NAME"

  # Shared-VM DNS routing — infra/api/src/startup.rs::init_dns_manager
  [cloudflare_api_token]="CLOUDFLARE_API_TOKEN"
  [cloudflare_zone_id]="CLOUDFLARE_ZONE_ID"
  [dns_domain]="DNS_DOMAIN"

  # Stripe — config.rs::from_reader (optional until Stage 7 activates them)
  [stripe_secret_key]="STRIPE_SECRET_KEY"
  [stripe_publishable_key]="STRIPE_PUBLISHABLE_KEY"
  [stripe_webhook_secret]="STRIPE_WEBHOOK_SECRET"
  [stripe_success_url]="STRIPE_SUCCESS_URL"
  [stripe_cancel_url]="STRIPE_CANCEL_URL"

  # Stripe plan prices — billing/src/plan.rs::EnvPlanRegistry
  [stripe_price_starter]="STRIPE_PRICE_STARTER"
  [stripe_price_pro]="STRIPE_PRICE_PRO"
  [stripe_price_enterprise]="STRIPE_PRICE_ENTERPRISE"

  # Cold storage — startup_env.rs
  [cold_bucket_name]="COLD_STORAGE_BUCKET"
  [cold_storage_prefix]="COLD_STORAGE_PREFIX"
  [cold_storage_region]="COLD_STORAGE_REGION"
  [cold_storage_endpoint]="COLD_STORAGE_ENDPOINT"
  [cold_storage_regions]="COLD_STORAGE_REGIONS"

  # Storage encryption — startup_env.rs
  [storage_encryption_key]="STORAGE_ENCRYPTION_KEY"

  # SES email — startup_env.rs
  [ses_from_address]="SES_FROM_ADDRESS"
  [ses_region]="SES_REGION"

  # Internal auth — config.rs::from_reader
  [internal_auth_token]="INTERNAL_AUTH_TOKEN"

  # Alert webhook URLs — read by infra/api/src/startup.rs::init_alert_service.
  [slack_webhook_url]="SLACK_WEBHOOK_URL"
  [discord_webhook_url]="DISCORD_WEBHOOK_URL"
)

# ---------------------------------------------------------------------------
# Static env vars (not from SSM — hardcoded per environment)
# These control startup_env.rs::is_local_zero_dependency_mode().
# ---------------------------------------------------------------------------

declare -A STATIC_VARS=(
  [ENVIRONMENT]="${ENV}"
  [NODE_SECRET_BACKEND]="ssm"
)

declare -A RESOLVED_VARS=()

# ---------------------------------------------------------------------------
# Fetch SSM parameters
# ---------------------------------------------------------------------------

echo "==> Fetching SSM parameters from ${SSM_PREFIX}/"

SSM_OUTPUT=$(aws ssm get-parameters-by-path \
  --path "${SSM_PREFIX}/" \
  --with-decryption \
  --region "$REGION" \
  --output json)

if [[ -z "$SSM_OUTPUT" ]]; then
  echo "ERROR: Failed to fetch SSM parameters from ${SSM_PREFIX}/"
  exit 1
fi

# ---------------------------------------------------------------------------
# Write /etc/fjcloud/env atomically
# ---------------------------------------------------------------------------

mkdir -p "$(dirname "$ENV_FILE")"

TMPFILE=$(mktemp "${ENV_FILE}.XXXXXX")

{
  printf '%s\n' "# Generated by generate_ssm_env.sh — do not edit manually"
  printf '%s\n' "# Environment: ${ENV}"
  printf '%s\n' "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""

  # Static vars first
  for var_name in "${!STATIC_VARS[@]}"; do
    RESOLVED_VARS["$var_name"]="${STATIC_VARS[$var_name]}"
    printf '%s\n' "${var_name}=${STATIC_VARS[$var_name]}"
  done
} > "$TMPFILE"

# SSM-sourced vars
MAPPED_COUNT=0
SKIPPED_LIST=()

while IFS= read -r line; do
  param_name=$(echo "$line" | cut -d'|' -f1)
  param_value=$(echo "$line" | cut -d'|' -f2-)

  # Extract suffix after /fjcloud/<env>/
  suffix="${param_name#${SSM_PREFIX}/}"

  if [[ -n "${SSM_TO_ENV[$suffix]+_}" ]]; then
    env_var="${SSM_TO_ENV[$suffix]}"
    RESOLVED_VARS["$env_var"]="$param_value"
    printf '%s\n' "${env_var}=${param_value}" >> "$TMPFILE"
    MAPPED_COUNT=$((MAPPED_COUNT + 1))
  else
    SKIPPED_LIST+=("${suffix}")
  fi
done < <(echo "$SSM_OUTPUT" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for p in data.get('Parameters', []):
    print(f\"{p['Name']}|{p['Value']}\")
")

chmod 0600 "$TMPFILE"
chown fjcloud:fjcloud "$TMPFILE" 2>/dev/null || true
mv "$TMPFILE" "$ENV_FILE"

echo "==> Wrote ${ENV_FILE} (${MAPPED_COUNT} SSM params mapped, static vars: ${#STATIC_VARS[@]})"
if [[ ${#SKIPPED_LIST[@]} -gt 0 ]]; then
  echo "    Skipped SSM params (no mapping):"
  printf '  %s\n' "${SKIPPED_LIST[@]}"
fi

# ---------------------------------------------------------------------------
# Write /etc/fjcloud/metering-env from the same owner chain + node metadata
# ---------------------------------------------------------------------------

fetch_imds_token() {
  curl -fsS -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"
}

imds_get() {
  local path="$1"
  local url="http://169.254.169.254/latest/${path}"
  if [[ -n "${IMDS_TOKEN:-}" ]]; then
    curl -fsS -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" "$url"
  else
    curl -fsS "$url"
  fi
}

IMDS_TOKEN="$(fetch_imds_token 2>/dev/null || true)"
INSTANCE_REGION="$(imds_get meta-data/placement/region 2>/dev/null || true)"
if [[ -n "$INSTANCE_REGION" ]]; then
  REGION="$INSTANCE_REGION"
fi

CUSTOMER_ID="$(imds_get meta-data/tags/instance/customer_id 2>/dev/null || true)"
NODE_ID="$(imds_get meta-data/tags/instance/node_id 2>/dev/null || true)"

if [[ -z "$CUSTOMER_ID" || "$CUSTOMER_ID" == "None" || "$CUSTOMER_ID" == "404 - Not Found" ]]; then
  echo "ERROR: missing required IMDS instance tag customer_id"
  exit 1
fi
if [[ -z "$NODE_ID" || "$NODE_ID" == "None" || "$NODE_ID" == "404 - Not Found" ]]; then
  echo "ERROR: missing required IMDS instance tag node_id"
  exit 1
fi

FLAPJACK_API_KEY=$(aws ssm get-parameter \
  --name "/fjcloud/${NODE_ID}/api-key" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text \
  --region "$REGION")

DATABASE_URL="${RESOLVED_VARS[DATABASE_URL]:-}"
DNS_DOMAIN="${RESOLVED_VARS[DNS_DOMAIN]:-}"
INTERNAL_KEY="${RESOLVED_VARS[INTERNAL_AUTH_TOKEN]:-${FLAPJACK_API_KEY}}"
ENVIRONMENT_VALUE="${RESOLVED_VARS[ENVIRONMENT]:-${ENV}}"
SLACK_WEBHOOK_URL="${RESOLVED_VARS[SLACK_WEBHOOK_URL]:-}"
DISCORD_WEBHOOK_URL="${RESOLVED_VARS[DISCORD_WEBHOOK_URL]:-}"

if [[ -z "$DATABASE_URL" ]]; then
  echo "ERROR: DATABASE_URL missing from ${ENV_FILE} mapping"
  exit 1
fi
if [[ -z "$DNS_DOMAIN" ]]; then
  echo "ERROR: DNS_DOMAIN missing from ${ENV_FILE} mapping"
  exit 1
fi

METERING_TMPFILE=$(mktemp "${METERING_ENV_FILE}.XXXXXX")

{
  printf '%s\n' "# Generated by generate_ssm_env.sh — do not edit manually"
  printf '%s\n' "# Environment: ${ENVIRONMENT_VALUE}"
  printf '%s\n' "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  printf '%s\n' "DATABASE_URL=${DATABASE_URL}"
  printf '%s\n' "FLAPJACK_URL=http://${NODE_ID}:7700"
  printf '%s\n' "FLAPJACK_API_KEY=${FLAPJACK_API_KEY}"
  printf '%s\n' "INTERNAL_KEY=${INTERNAL_KEY}"
  printf '%s\n' "CUSTOMER_ID=${CUSTOMER_ID}"
  printf '%s\n' "NODE_ID=${NODE_ID}"
  printf '%s\n' "REGION=${REGION}"
  printf '%s\n' "ENVIRONMENT=${ENVIRONMENT_VALUE}"
  printf '%s\n' "TENANT_MAP_URL=https://api.${DNS_DOMAIN}/internal/tenant-map"
  printf '%s\n' "COLD_STORAGE_USAGE_URL=https://api.${DNS_DOMAIN}/internal/cold-storage-usage"
  printf '%s\n' "SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}"
  printf '%s\n' "DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}"
} > "$METERING_TMPFILE"

chmod 0600 "$METERING_TMPFILE"
chown fjcloud:fjcloud "$METERING_TMPFILE" 2>/dev/null || true
mv "$METERING_TMPFILE" "$METERING_ENV_FILE"

echo "==> Wrote ${METERING_ENV_FILE} (metering runtime contract)"
