#!/usr/bin/env bash
# generate_ssm_env.sh — Read SSM parameters and write /etc/fjcloud/env
#
# Single source of truth for the SSM-param-name → env-var-name mapping.
# Called on-instance before service restart to populate the EnvironmentFile
# referenced by systemd units (fjcloud-api.service, fjcloud-aggregation-job.service).
#
# Usage: generate_ssm_env.sh <env>
#   env: staging | prod
#
# Requires: aws CLI with IAM role that can ssm:GetParametersByPath + kms:Decrypt.

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: generate_ssm_env.sh <env>"
  exit 1
fi

ENV="$1"
REGION="${AWS_DEFAULT_REGION:-us-east-1}"
SSM_PREFIX="/fjcloud/${ENV}"
ENV_FILE="/etc/fjcloud/env"

if [[ "$ENV" != "staging" && "$ENV" != "prod" ]]; then
  echo "ERROR: env must be 'staging' or 'prod' (got: ${ENV})"
  exit 1
fi

# ---------------------------------------------------------------------------
# SSM param name → env var name mapping
#
# Keys are the SSM parameter suffix (after /fjcloud/<env>/).
# Values are the env var names that infra/api/src/config.rs::from_reader and
# infra/api/src/startup_env.rs::StartupEnvSnapshot expect.
#
# Parameters NOT in this map are skipped (e.g., last_deploy_sha, db_password).
# ---------------------------------------------------------------------------

declare -A SSM_TO_ENV=(
  # Required by config.rs::from_reader
  [database_url]="DATABASE_URL"
  [jwt_secret]="JWT_SECRET"
  [admin_key]="ADMIN_KEY"

  # Shared-VM provisioning — infra/api/src/provisioner/aws.rs
  [aws_ami_id]="AWS_AMI_ID"
  [aws_subnet_id]="AWS_SUBNET_ID"
  [aws_security_group_ids]="AWS_SECURITY_GROUP_IDS"
  [aws_key_pair_name]="AWS_KEY_PAIR_NAME"
  [aws_instance_profile_name]="AWS_INSTANCE_PROFILE_NAME"

  # Shared-VM DNS routing — infra/api/src/startup.rs::init_dns_manager
  [cloudflare_api_token]="CLOUDFLARE_API_TOKEN"
  [cloudflare_zone_id]="CLOUDFLARE_ZONE_ID"
  [dns_domain]="DNS_DOMAIN"

  # Stripe — config.rs::from_reader (optional until Stage 7 activates them)
  [stripe_secret_key]="STRIPE_SECRET_KEY"
  [stripe_publishable_key]="STRIPE_PUBLISHABLE_KEY"
  [stripe_webhook_secret]="STRIPE_WEBHOOK_SECRET"
  [stripe_success_url]="STRIPE_SUCCESS_URL"
  [stripe_cancel_url]="STRIPE_CANCEL_URL"

  # Stripe plan prices — billing/src/plan.rs::EnvPlanRegistry
  [stripe_price_starter]="STRIPE_PRICE_STARTER"
  [stripe_price_pro]="STRIPE_PRICE_PRO"
  [stripe_price_enterprise]="STRIPE_PRICE_ENTERPRISE"

  # Cold storage — startup_env.rs
  [cold_bucket_name]="COLD_STORAGE_BUCKET"
  [cold_storage_prefix]="COLD_STORAGE_PREFIX"
  [cold_storage_region]="COLD_STORAGE_REGION"
  [cold_storage_endpoint]="COLD_STORAGE_ENDPOINT"
  [cold_storage_regions]="COLD_STORAGE_REGIONS"

  # Storage encryption — startup_env.rs
  [storage_encryption_key]="STORAGE_ENCRYPTION_KEY"

  # SES email — startup_env.rs
  [ses_from_address]="SES_FROM_ADDRESS"
  [ses_region]="SES_REGION"

  # Internal auth — config.rs::from_reader
  [internal_auth_token]="INTERNAL_AUTH_TOKEN"
)

# ---------------------------------------------------------------------------
# Static env vars (not from SSM — hardcoded per environment)
# These control startup_env.rs::is_local_zero_dependency_mode().
# ---------------------------------------------------------------------------

declare -A STATIC_VARS=(
  [ENVIRONMENT]="${ENV}"
  [NODE_SECRET_BACKEND]="ssm"
)

# ---------------------------------------------------------------------------
# Fetch SSM parameters
# ---------------------------------------------------------------------------

echo "==> Fetching SSM parameters from ${SSM_PREFIX}/"

SSM_OUTPUT=$(aws ssm get-parameters-by-path \
  --path "${SSM_PREFIX}/" \
  --with-decryption \
  --region "$REGION" \
  --output json)

if [[ -z "$SSM_OUTPUT" ]]; then
  echo "ERROR: Failed to fetch SSM parameters from ${SSM_PREFIX}/"
  exit 1
fi

# ---------------------------------------------------------------------------
# Build env file content
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Write env file atomically
#
# Write lines directly with printf '%s\n' instead of building a string and
# using printf '%b', which would corrupt values containing backslash sequences
# (e.g., \n, \t in DATABASE_URL passwords or encryption keys).
# ---------------------------------------------------------------------------

mkdir -p "$(dirname "$ENV_FILE")"

TMPFILE=$(mktemp "${ENV_FILE}.XXXXXX")

{
  printf '%s\n' "# Generated by generate_ssm_env.sh — do not edit manually"
  printf '%s\n' "# Environment: ${ENV}"
  printf '%s\n' "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""

  # Static vars first
  for var_name in "${!STATIC_VARS[@]}"; do
    printf '%s\n' "${var_name}=${STATIC_VARS[$var_name]}"
  done
} > "$TMPFILE"

# SSM-sourced vars
MAPPED_COUNT=0
SKIPPED_LIST=()

while IFS= read -r line; do
  param_name=$(echo "$line" | cut -d'|' -f1)
  param_value=$(echo "$line" | cut -d'|' -f2-)

  # Extract suffix after /fjcloud/<env>/
  suffix="${param_name#${SSM_PREFIX}/}"

  if [[ -n "${SSM_TO_ENV[$suffix]+_}" ]]; then
    env_var="${SSM_TO_ENV[$suffix]}"
    printf '%s\n' "${env_var}=${param_value}" >> "$TMPFILE"
    MAPPED_COUNT=$((MAPPED_COUNT + 1))
  else
    SKIPPED_LIST+=("${suffix}")
  fi
done < <(echo "$SSM_OUTPUT" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for p in data.get('Parameters', []):
    print(f\"{p['Name']}|{p['Value']}\")
")
chmod 0600 "$TMPFILE"
chown fjcloud:fjcloud "$TMPFILE" 2>/dev/null || true
mv "$TMPFILE" "$ENV_FILE"

echo "==> Wrote ${ENV_FILE} (${MAPPED_COUNT} SSM params mapped, static vars: ${#STATIC_VARS[@]})"
if [[ ${#SKIPPED_LIST[@]} -gt 0 ]]; then
  echo "    Skipped SSM params (no mapping):"
  printf '  %s\n' "${SKIPPED_LIST[@]}"
fi
