#!/usr/bin/env bash
# scripts/probe_live_state.sh — fjcloud realization of Live State Discipline.
#
# Per-project read-only inventory probe. Hits every external mutable-state surface
# fjcloud touches (Stripe, AWS SNS/SSM, Cloudflare DNS/Pages, staging RDS, staging
# API health, Privacy.com) and writes a dated snapshot to docs/live-state/<ts>/
# with a SUMMARY.md downstream lanes consume.
#
# CONTRACT (read these before changing):
# - Read-only. No mutations. Exit 0 ALWAYS (data, not enforcement — per discipline).
# - Per-section errors → status=PROBE_ERROR in SUMMARY (distinct from ACTION_REQUIRED).
# - Missing creds for a section → status=SKIP_NO_CREDS (distinct from PROBE_ERROR).
# - Idempotent per UTC-second; re-runs in same second overwrite same TS dir.
# - The script ships to public mirrors (scripts/ is whitelisted in .debbie.toml).
#   Therefore: NO absolute operator-machine paths, NO hardcoded AWS account IDs, NO
#   embedded secrets. The probe's OUTPUTS land under docs/live-state/ which
#   IS excluded from public mirrors.
#
# DISCIPLINE: see ~/.matt/scrai/globals/standards/live_state_discipline.md
# This is a state-inventory probe. Behavioral assumptions (signup → token
# verification, etc.) belong in scripts/canary/contracts/ — separate concern.
#
# REUSE:
# - scripts/lib/stripe_checks.sh — check_stripe_key_live (sourced via subshell
#   only; it runs `set -euo pipefail` at top level + `exit 124` on timeout,
#   which would break this script's exit-0-always discipline if sourced directly).
# - scripts/lib/live_gate.sh — not currently sourced; live_gate_* helpers exist
#   but the probe doesn't need OK/SKIP gating semantics.
#
# OVERRIDE: FJCLOUD_SECRET_FILE may override the default ./.secret/.env.secret path.
# Default follows CLAUDE.md secrets contract (repo-local .secret/.env.secret).
#
# SUMMARY.md row format (downstream A4 + A5.3 + Wave 1 lanes parse this):
#   ### <vendor_id>
#   - status: OK|DRIFT|STALE|ACTION_REQUIRED|PROBE_ERROR|SKIP_NO_CREDS
#   - agent_executable: true|false       # filter for A5.3 automated diff
#   - finding: <one-line>
#   - raw: <relative path to raw subfile>
#
# manifest.txt lists every raw subfile this run produced — A2.3 validation
# uses the manifest (not glob) so empty-but-valid vendor responses don't false-fail.

set -uo pipefail
# NOTE: deliberately NOT `set -e` — per-vendor errors must not abort the script.
# Each section captures its own error state into the SUMMARY.

# ---------------------------------------------------------------------------
# 0. Bootstrap
# ---------------------------------------------------------------------------

SECRET_FILE="${FJCLOUD_SECRET_FILE:-./.secret/.env.secret}"
if [ ! -f "$SECRET_FILE" ]; then
  echo "FAIL_NO_SECRETS: $SECRET_FILE not found" >&2
  echo "Set FJCLOUD_SECRET_FILE or run from the dev-repo root" >&2
  exit 2
fi
# Auto-export sourced vars so subprocesses (aws CLI, curl) inherit them.
# .env.secret entries are `KEY=VALUE` (no explicit export), so without `set -a`
# they would be shell-local only and the AWS CLI subprocess would fail with
# "Unable to locate credentials" despite the vars being set in the script.
set -a
# shellcheck disable=SC1090
source "$SECRET_FILE"
set +a

TS="$(date -u +%Y%m%dT%H%M%SZ)"
OUT="docs/live-state/$TS"
mkdir -p "$OUT"

SUMMARY="$OUT/SUMMARY.md"
MANIFEST="$OUT/manifest.txt"
: > "$MANIFEST"   # truncate

cat > "$SUMMARY" <<EOF
# fjcloud live-state snapshot — $TS

Generated by \`scripts/probe_live_state.sh\` per [Live State Discipline](~/.matt/scrai/globals/standards/live_state_discipline.md).

Row format: \`status\` ∈ {OK, DRIFT, STALE, ACTION_REQUIRED, PROBE_ERROR, SKIP_NO_CREDS};
\`agent_executable: true\` rows are fixable by the inline agent and must flip to OK
by Phase A's end (per A5.3); \`agent_executable: false\` rows go to the operator
playbook.

EOF

# Helper: append a SUMMARY row. Args: vendor_id, status, agent_executable, finding, raw_file
add_row() {
  local vendor="$1" status="$2" ae="$3" finding="$4" raw="$5"
  {
    printf '### %s\n' "$vendor"
    printf -- '- status: %s\n' "$status"
    printf -- '- agent_executable: %s\n' "$ae"
    printf -- '- finding: %s\n' "$finding"
    printf -- '- raw: %s\n\n' "$raw"
  } >> "$SUMMARY"
}

# Helper: register a raw subfile in the manifest (relative to $OUT).
register_raw() {
  printf '%s\n' "$1" >> "$MANIFEST"
}

# ---------------------------------------------------------------------------
# 1. AWS identity (gates all AWS-touching sections)
# ---------------------------------------------------------------------------
# Resolve account ID at runtime — never hardcode (the script ships to public mirrors).
# If credentials are bad, every AWS section writes SKIP_NO_CREDS rather than
# constructing a bogus ARN that gets a confusing parser error from the AWS CLI.

AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text 2>/dev/null || true)"
AWS_OK=0
if [ -n "$AWS_ACCOUNT_ID" ] && [ "$AWS_ACCOUNT_ID" != "None" ]; then
  AWS_OK=1
fi

# ---------------------------------------------------------------------------
# 2. Stripe — probe each key's liveness via check_stripe_key_live (sourced in subshell)
# ---------------------------------------------------------------------------
# Probe TEST-mode keys only. The RESTRICTED_LIVE key is live-mode; we do NOT
# call against live mode from an inventory probe (CLAUDE.md "Stripe testing"
# rule: test mode is free, do not invoke against live mode).
# Pairs: (label_for_SUMMARY, env-var-name-in-.env.secret)
STRIPE_PROBE_KEYS=(
  "stripe_canonical:STRIPE_SECRET_KEY"
  "stripe_restricted:STRIPE_SECRET_KEY_RESTRICTED"
)

for pair in "${STRIPE_PROBE_KEYS[@]}"; do
  label="${pair%%:*}"
  varname="${pair##*:}"
  raw_file="$OUT/${label}.txt"
  register_raw "${label}.txt"
  : > "$raw_file"

  key_val="${!varname:-}"
  if [ -z "$key_val" ]; then
    echo "SKIP_NO_CREDS: env var $varname is empty or unset" > "$raw_file"
    add_row "$label" "SKIP_NO_CREDS" "false" "env var $varname not present in .env.secret" "${label}.txt"
    continue
  fi

  # Probe via check_stripe_key_live in a subshell so its set -euo pipefail
  # and any exit calls don't infect this script.
  #
  # CRITICAL: set BACKEND_LIVE_GATE=1 inside the subshell. Without it,
  # check_stripe_key_live's failure paths call live_gate_fail_with_reason
  # which returns 0 when the gate is off — producing a SILENT FALSE POSITIVE
  # for any broken/dead key (verified empirically with a bogus key). With
  # the gate on, the function exits 1 on auth failure, the subshell exits 1,
  # and the parent probe catches it via probe_rc≠0 — terminating at the
  # actual Stripe HTTP response, not at the function's no-op exit.
  probe_rc=0
  probe_out="$(
    (
      STRIPE_SECRET_KEY="$key_val"
      BACKEND_LIVE_GATE=1
      # shellcheck disable=SC1091
      source scripts/lib/stripe_checks.sh
      check_stripe_key_live 2>&1
    )
  )" || probe_rc=$?

  {
    echo "label=$label"
    echo "env_var=$varname"
    echo "key_prefix=${key_val:0:8}..."   # never the full key
    echo "probe_exit_code=$probe_rc"
    echo "--- probe output ---"
    echo "$probe_out"
  } > "$raw_file"

  if [ "$probe_rc" -eq 0 ]; then
    add_row "$label" "OK" "false" "Stripe key authenticates against GET /v1/balance" "${label}.txt"
  else
    # check_stripe_key_live emits structured REASON: codes (see stripe_checks.sh:11-25)
    finding="Stripe key probe failed (rc=$probe_rc) — see raw"
    add_row "$label" "ACTION_REQUIRED" "false" "$finding" "${label}.txt"
  fi
done

# Stripe webhook_endpoints — enumerate per environment (test mode only)
# Confirms which webhook endpoints Stripe has registered for the test-mode account.
# Uses STRIPE_SECRET_KEY (test-mode) for the API call.
raw_file="$OUT/stripe_webhook_endpoints.txt"
register_raw "stripe_webhook_endpoints.txt"
if [ -n "${STRIPE_SECRET_KEY:-}" ]; then
  http_status="$(curl -s -o "$OUT/stripe_webhook_endpoints.body.json" -w '%{http_code}' \
    --max-time 10 \
    -u "${STRIPE_SECRET_KEY}:" \
    "https://api.stripe.com/v1/webhook_endpoints?limit=20" 2>/dev/null || echo "000")"
  register_raw "stripe_webhook_endpoints.body.json"
  {
    echo "http_status=$http_status"
    if [ "$http_status" = "200" ] && command -v python3 >/dev/null; then
      python3 -c '
import json
d = json.load(open("'"$OUT/stripe_webhook_endpoints.body.json"'"))
for e in d.get("data", []):
    eid = e.get("id")
    url = e.get("url")
    st = e.get("status")
    ev = len(e.get("enabled_events", []))
    print("- id={} url={} status={} events={}".format(eid, url, st, ev))
print("total: {}".format(len(d.get("data", []))))
'
    fi
  } > "$raw_file"
  if [ "$http_status" = "200" ]; then
    count=$(python3 -c 'import json;print(len(json.load(open("'"$OUT/stripe_webhook_endpoints.body.json"'")).get("data",[])))' 2>/dev/null || echo "?")
    add_row "stripe_webhook_endpoints" "OK" "false" "$count Stripe webhook endpoints registered (test mode)" "stripe_webhook_endpoints.txt"
  else
    add_row "stripe_webhook_endpoints" "PROBE_ERROR" "false" "Stripe /v1/webhook_endpoints returned HTTP $http_status" "stripe_webhook_endpoints.txt"
  fi
else
  echo "SKIP_NO_CREDS: STRIPE_SECRET_KEY unset" > "$raw_file"
  add_row "stripe_webhook_endpoints" "SKIP_NO_CREDS" "false" "STRIPE_SECRET_KEY unset" "stripe_webhook_endpoints.txt"
fi

# Webhook secret — just presence + prefix check (no live call from inventory)
raw_file="$OUT/stripe_webhook_secret.txt"
register_raw "stripe_webhook_secret.txt"
if [ -n "${STRIPE_WEBHOOK_SECRET:-}" ]; then
  prefix="${STRIPE_WEBHOOK_SECRET:0:6}"
  echo "prefix=$prefix" > "$raw_file"
  if [ "$prefix" = "whsec_" ]; then
    add_row "stripe_webhook_secret" "OK" "false" "STRIPE_WEBHOOK_SECRET present with whsec_ prefix" "stripe_webhook_secret.txt"
  else
    add_row "stripe_webhook_secret" "ACTION_REQUIRED" "false" "STRIPE_WEBHOOK_SECRET has wrong prefix" "stripe_webhook_secret.txt"
  fi
else
  echo "unset" > "$raw_file"
  add_row "stripe_webhook_secret" "SKIP_NO_CREDS" "false" "STRIPE_WEBHOOK_SECRET unset" "stripe_webhook_secret.txt"
fi

# Note: STRIPE_SECRET_KEY_RESTRICTED_LIVE is intentionally NOT probed (live-mode key).
# Record its presence only.
raw_file="$OUT/stripe_restricted_live_presence.txt"
register_raw "stripe_restricted_live_presence.txt"
if [ -n "${STRIPE_SECRET_KEY_RESTRICTED_LIVE:-}" ]; then
  echo "present (live-mode key — NOT probed against API)" > "$raw_file"
  add_row "stripe_restricted_live_presence" "OK" "false" "Live-mode restricted key present; not probed (test-mode only policy)" "stripe_restricted_live_presence.txt"
else
  echo "unset" > "$raw_file"
  add_row "stripe_restricted_live_presence" "STALE" "false" "STRIPE_SECRET_KEY_RESTRICTED_LIVE absent — may be intentional" "stripe_restricted_live_presence.txt"
fi

# Stripe account configuration — statement descriptor + business profile.
# Operator sets these in the Stripe Dashboard; this probe verifies the
# API-readable subset via GET /v1/account. Customer-Emails toggles
# (invoice receipts, dunning, expiring-card) are NOT exposed by this endpoint
# and must be operator-verified per docs/runbooks/paid_beta_rc_signoff.md
# "Stripe Dashboard Prerequisites".
raw_file="$OUT/stripe_account_config.txt"
register_raw "stripe_account_config.txt"
if [ -n "${STRIPE_SECRET_KEY:-}" ]; then
  http_status="$(curl -s -o "$OUT/stripe_account_config.body.json" -w '%{http_code}' \
    --max-time 10 \
    -u "${STRIPE_SECRET_KEY}:" \
    "https://api.stripe.com/v1/account" 2>/dev/null || echo "000")"
  register_raw "stripe_account_config.body.json"
  {
    echo "http_status=$http_status"
    if [ "$http_status" = "200" ] && command -v python3 >/dev/null; then
      python3 -c '
import json
d = json.load(open("'"$OUT/stripe_account_config.body.json"'"))
sd = d.get("settings", {}).get("payments", {}).get("statement_descriptor", "")
bp = d.get("business_profile") or {}
support = bp.get("support_email", "")
url = bp.get("url", "")
name = bp.get("name", "")
print("statement_descriptor:", sd or "(unset)")
print("business_profile.support_email:", support or "(unset)")
print("business_profile.url:", url or "(unset)")
print("business_profile.name:", name or "(unset)")
missing = [k for k, v in [("statement_descriptor", sd), ("support_email", support), ("business_url", url), ("business_name", name)] if not v]
print("missing:", ",".join(missing) if missing else "(none)")
'
    fi
  } > "$raw_file"
  if [ "$http_status" = "200" ]; then
    missing_line="$(grep '^missing:' "$raw_file" | sed 's/^missing: //')"
    if [ "$missing_line" = "(none)" ]; then
      add_row "stripe_account_config" "OK" "false" "statement descriptor + business profile complete" "stripe_account_config.txt"
    else
      add_row "stripe_account_config" "ACTION_REQUIRED" "false" "Stripe Dashboard missing: $missing_line (operator action — see docs/runbooks/paid_beta_rc_signoff.md Stripe Dashboard Prerequisites)" "stripe_account_config.txt"
    fi
  else
    add_row "stripe_account_config" "PROBE_ERROR" "false" "Stripe /v1/account returned HTTP $http_status" "stripe_account_config.txt"
  fi
else
  echo "STRIPE_SECRET_KEY unset" > "$raw_file"
  add_row "stripe_account_config" "SKIP_NO_CREDS" "false" "STRIPE_SECRET_KEY unset" "stripe_account_config.txt"
fi

# ---------------------------------------------------------------------------
# 3. AWS SNS — fjcloud-alerts subscriptions per environment
# ---------------------------------------------------------------------------

for env in staging prod; do
  raw_file="$OUT/aws_sns_${env}.txt"
  register_raw "aws_sns_${env}.txt"
  vendor_id="aws_sns_${env}"

  if [ "$AWS_OK" -eq 0 ]; then
    echo "SKIP_NO_CREDS: aws sts get-caller-identity failed" > "$raw_file"
    add_row "$vendor_id" "SKIP_NO_CREDS" "false" "AWS credentials not resolvable" "aws_sns_${env}.txt"
    continue
  fi

  topic_arn="arn:aws:sns:us-east-1:${AWS_ACCOUNT_ID}:fjcloud-alerts-${env}"
  subs_out="$(aws sns list-subscriptions-by-topic --topic-arn "$topic_arn" --output json 2>&1)"
  subs_rc=$?

  {
    echo "topic=$topic_arn"
    echo "list_exit_code=$subs_rc"
    echo "--- subscriptions ---"
    echo "$subs_out"
  } > "$raw_file"

  if [ "$subs_rc" -ne 0 ]; then
    add_row "$vendor_id" "PROBE_ERROR" "false" "aws sns list failed for $topic_arn" "aws_sns_${env}.txt"
    continue
  fi

  # Count subscriptions in various states
  total=$(echo "$subs_out" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(len(d.get("Subscriptions",[])))' 2>/dev/null || echo "?")
  pending=$(echo "$subs_out" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(sum(1 for s in d.get("Subscriptions",[]) if s.get("SubscriptionArn")=="PendingConfirmation"))' 2>/dev/null || echo "?")

  # Cross-check pending-confirmation endpoints against the canonical
  # declined-recipients list at docs/decisions/2026_05_22_alert_email_recipients.md.
  # Pending-confirmation entries for explicitly-declined addresses are NOT drift
  # — the operator already decided against them; treating them as DRIFT was the
  # exact stale-claim-relay pattern Live State Discipline forbids.
  decision_file="docs/decisions/2026_05_22_alert_email_recipients.md"
  pending_undecided=0
  if [ "$pending" != "0" ] && [ -f "$decision_file" ] && command -v python3 >/dev/null; then
    # Extract pending-confirmation emails from the subs JSON
    pending_emails="$(echo "$subs_out" | python3 -c '
import json,sys
d = json.load(sys.stdin)
for s in d.get("Subscriptions", []):
    if s.get("SubscriptionArn") == "PendingConfirmation":
        print(s.get("Endpoint",""))
' 2>/dev/null || true)"
    # Extract declined list from the decision file. The header is "## Declined ...";
    # we extract lines BETWEEN it and the next "## " heading. The naive
    # awk-range pattern would match only the header line (which itself matches
    # the terminator); use a flag-based state machine instead.
    declined_emails="$(awk '/^## Declined/{flag=1;next} /^## /{flag=0} flag' "$decision_file" | grep -oE '`[^`]+@[^`]+`' | tr -d '`')"
    for em in $pending_emails; do
      if ! echo "$declined_emails" | grep -qFx "$em"; then
        pending_undecided=$((pending_undecided + 1))
      fi
    done
  else
    pending_undecided="$pending"
  fi

  if [ "$pending" = "0" ]; then
    add_row "$vendor_id" "OK" "false" "$total subscriptions, 0 pending-confirmation" "aws_sns_${env}.txt"
  elif [ "$pending_undecided" -eq 0 ]; then
    # All pending entries are explicitly declined recipients — stale invites that
    # auto-expire in 3 days; not an operator action.
    add_row "$vendor_id" "OK" "false" "$total subscriptions, $pending pending-confirmation (all are explicitly-declined per docs/decisions/2026_05_22_alert_email_recipients.md — auto-expire in 3 days, no action)" "aws_sns_${env}.txt"
  else
    # Genuinely-undecided pending subs (new addresses not in the decision file).
    # PendingConfirmation subs cannot be deleted via AWS CLI — operator must
    # confirm/cancel via email or wait 3-day auto-expiration.
    add_row "$vendor_id" "DRIFT" "false" "$total subscriptions, $pending pending-confirmation ($pending_undecided NOT in decision file — operator decision needed)" "aws_sns_${env}.txt"
  fi
done

# ---------------------------------------------------------------------------
# 4. AWS SSM — critical parameter freshness (no values captured)
# ---------------------------------------------------------------------------

# Verified at probe-build time against `aws ssm get-parameters-by-path --recursive`:
# the actual param name is `stripe_webhook_secret` (NOT `stripe_webhook_signing_secret`).
# All listed params exist on both staging and prod.
SSM_PARAMS=(
  "jwt_secret"
  "stripe_secret_key"
  "stripe_webhook_secret"
  "google_oauth_client_secret"
  "github_oauth_client_secret"
  "app_base_url"
)

for env in staging prod; do
  raw_file="$OUT/aws_ssm_${env}.txt"
  register_raw "aws_ssm_${env}.txt"
  vendor_id="aws_ssm_${env}"
  : > "$raw_file"

  if [ "$AWS_OK" -eq 0 ]; then
    echo "SKIP_NO_CREDS: aws sts get-caller-identity failed" > "$raw_file"
    add_row "$vendor_id" "SKIP_NO_CREDS" "false" "AWS credentials not resolvable" "aws_ssm_${env}.txt"
    continue
  fi

  param_errors=0
  param_count=0
  for param in "${SSM_PARAMS[@]}"; do
    param_count=$((param_count + 1))
    full_name="/fjcloud/${env}/${param}"
    # Capture Version + LastModifiedDate only; never Value (security).
    meta="$(aws ssm get-parameter --name "$full_name" --query 'Parameter.{Version:Version,LastModifiedDate:LastModifiedDate}' --output json 2>&1)"
    meta_rc=$?
    {
      echo "=== $full_name ==="
      if [ "$meta_rc" -eq 0 ]; then
        echo "$meta"
      else
        echo "ERROR (rc=$meta_rc): $meta"
        param_errors=$((param_errors + 1))
      fi
    } >> "$raw_file"
  done

  if [ "$param_errors" -eq 0 ]; then
    add_row "$vendor_id" "OK" "false" "all $param_count SSM params readable (metadata only)" "aws_ssm_${env}.txt"
  else
    add_row "$vendor_id" "DRIFT" "false" "$param_errors of $param_count SSM params failed (missing or unauthorized)" "aws_ssm_${env}.txt"
  fi
done

# ---------------------------------------------------------------------------
# 5. Cloudflare DNS — check key hosts resolve
# ---------------------------------------------------------------------------

raw_file="$OUT/cloudflare_dns.txt"
register_raw "cloudflare_dns.txt"
: > "$raw_file"

dns_hosts=(
  "api.flapjack.foo"
  "api.staging.flapjack.foo"
  "cloud.flapjack.foo"
  "cloud.staging.flapjack.foo"
)
dns_errors=0
for host in "${dns_hosts[@]}"; do
  result="$(dig +short A "$host" @1.1.1.1 2>&1)"
  {
    echo "=== $host ==="
    echo "$result"
  } >> "$raw_file"
  if [ -z "$result" ]; then
    dns_errors=$((dns_errors + 1))
  fi
done
if [ "$dns_errors" -eq 0 ]; then
  add_row "cloudflare_dns" "OK" "false" "all 4 hosts resolve" "cloudflare_dns.txt"
else
  add_row "cloudflare_dns" "DRIFT" "false" "$dns_errors of 4 hosts failed to resolve" "cloudflare_dns.txt"
fi

# ---------------------------------------------------------------------------
# 6. Cloudflare Pages — list env vars (names only, no values)
# ---------------------------------------------------------------------------
# Uses the global-key + email auth that fjcloud's .env.secret carries
# (CLOUDFLARE_GLOBAL_API_KEY + CLOUDFLARE_EMAIL). If absent → SKIP_NO_CREDS.

raw_file="$OUT/cloudflare_pages.txt"
register_raw "cloudflare_pages.txt"
: > "$raw_file"

if [ -z "${CLOUDFLARE_GLOBAL_API_KEY:-}" ] || [ -z "${CLOUDFLARE_EMAIL:-}" ]; then
  echo "SKIP_NO_CREDS: CLOUDFLARE_GLOBAL_API_KEY and/or CLOUDFLARE_EMAIL missing" > "$raw_file"
  add_row "cloudflare_pages" "SKIP_NO_CREDS" "false" "Cloudflare credentials missing in .env.secret" "cloudflare_pages.txt"
else
  # Step 1: resolve account ID via list-accounts.
  acct_http="$(curl -s -o "$OUT/cf_accounts.json" -w '%{http_code}' \
    -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
    -H "X-Auth-Key: $CLOUDFLARE_GLOBAL_API_KEY" \
    https://api.cloudflare.com/client/v4/accounts)"
  register_raw "cf_accounts.json"

  # Capture the FIRST account id (Cloudflare returns paginated; we want one).
  acct_id=""
  if [ "$acct_http" = "200" ] && command -v python3 >/dev/null; then
    acct_id="$(python3 -c '
import json
d = json.load(open("'"$OUT/cf_accounts.json"'"))
ids = [a["id"] for a in d.get("result", [])]
print(ids[0] if ids else "")
' 2>/dev/null || true)"
  fi

  {
    echo "list_accounts_http_status=$acct_http"
    echo "account_id_resolved=${acct_id:-NONE}"
  } > "$raw_file"

  if [ -z "$acct_id" ]; then
    add_row "cloudflare_pages" "PROBE_ERROR" "false" "Cloudflare list-accounts returned HTTP $acct_http or yielded no account_id" "cloudflare_pages.txt"
  else
    # Step 2: list Pages projects under this account.
    proj_http="$(curl -s -o "$OUT/cf_pages_projects.json" -w '%{http_code}' \
      -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
      -H "X-Auth-Key: $CLOUDFLARE_GLOBAL_API_KEY" \
      "https://api.cloudflare.com/client/v4/accounts/${acct_id}/pages/projects")"
    register_raw "cf_pages_projects.json"

    if [ "$proj_http" = "200" ] && command -v python3 >/dev/null; then
      # For each project, list env-var NAMES (not values).
      python3 -c '
import json,sys
d = json.load(open("'"$OUT/cf_pages_projects.json"'"))
for p in d.get("result", []):
    name = p.get("name", "?")
    envs = p.get("deployment_configs", {})
    for env in ("production", "preview"):
        vars_obj = envs.get(env, {}).get("env_vars") or {}
        names = sorted(vars_obj.keys()) if isinstance(vars_obj, dict) else []
        print(f"- project={name} env={env} var_count={len(names)} names={names}")
' >> "$raw_file" 2>&1
      add_row "cloudflare_pages" "OK" "false" "Cloudflare Pages projects + env-var names enumerated (values NOT captured)" "cloudflare_pages.txt"
    else
      add_row "cloudflare_pages" "PROBE_ERROR" "false" "Pages projects list returned HTTP $proj_http" "cloudflare_pages.txt"
    fi
  fi
fi

# ---------------------------------------------------------------------------
# 7. Staging API + prod API health
# ---------------------------------------------------------------------------

raw_file="$OUT/api_health.txt"
register_raw "api_health.txt"
: > "$raw_file"

# Use `|` as separator (URLs contain `:`, so `${pair##*:}` would mangle them).
api_hosts=(
  "staging|https://api.staging.flapjack.foo/health"
  "prod|https://api.flapjack.foo/health"
)
api_errors=0
for pair in "${api_hosts[@]}"; do
  env="${pair%%|*}"
  url="${pair##*|}"
  body_file="$OUT/api_health_${env}.body"
  register_raw "api_health_${env}.body"
  http_status="$(curl -s -o "$body_file" -w '%{http_code}' --max-time 10 "$url" 2>/dev/null || true)"
  [ -n "$http_status" ] || http_status="000"
  {
    echo "=== $env $url ==="
    echo "http_status=$http_status"
    if [ -f "$body_file" ]; then
      echo "body_bytes=$(wc -c < "$body_file" | tr -d ' ')"
    fi
  } >> "$raw_file"
  if [ "$http_status" != "200" ]; then
    api_errors=$((api_errors + 1))
  fi
done

if [ "$api_errors" -eq 0 ]; then
  add_row "api_health" "OK" "false" "both staging + prod /health return 200" "api_health.txt"
else
  add_row "api_health" "ACTION_REQUIRED" "false" "$api_errors of 2 /health endpoints not 200" "api_health.txt"
fi

# ---------------------------------------------------------------------------
# 8. Staging RDS — customer count + test-pattern emails
# ---------------------------------------------------------------------------
# Shells out to scripts/launch/ssm_exec_staging.sh (the existing SSM-exec
# pattern used by web/tests/fixtures/staging_db_lookup.ts).

raw_file="$OUT/staging_rds.txt"
register_raw "staging_rds.txt"
: > "$raw_file"

ssm_exec="scripts/launch/ssm_exec_staging.sh"
if [ ! -x "$ssm_exec" ]; then
  echo "SKIP_NO_CREDS: $ssm_exec missing or not executable" > "$raw_file"
  add_row "staging_rds" "SKIP_NO_CREDS" "false" "ssm_exec_staging.sh not available" "staging_rds.txt"
elif [ "$AWS_OK" -eq 0 ]; then
  echo "SKIP_NO_CREDS: AWS credentials missing (ssm_exec requires AWS access)" > "$raw_file"
  add_row "staging_rds" "SKIP_NO_CREDS" "false" "AWS credentials not resolvable" "staging_rds.txt"
else
  # ssm_exec_staging.sh receives a shell command (not raw SQL); it runs that
  # command on the staging API EC2 instance where DATABASE_URL is reachable.
  # Wrap each query in the canonical `source /etc/fjcloud/env && psql ... -tAc "..."`
  # pattern that `web/tests/fixtures/staging_db_lookup.ts::buildSsmStagingPsqlCommand`
  # uses — verified at probe-build time against the actual deployed env layout.
  #
  # macOS does not ship GNU `timeout`. Use bash background + sleep + kill so the
  # probe is portable across macOS + Linux CI environments.
  q1='source /etc/fjcloud/env && psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -tAc "SELECT COUNT(*) FROM customers WHERE status != '"'"'deleted'"'"'"'
  q2='source /etc/fjcloud/env && psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -tAc "SELECT COUNT(*) FROM customers WHERE (email LIKE '"'"'signup-paid-%@%'"'"' OR email LIKE '"'"'%-test@flapjack-test.example'"'"') AND status != '"'"'deleted'"'"'"'

  # Helper: run a shell command with a wall-clock timeout, capture all output.
  # Returns the command's exit code, or 124 on timeout.
  run_with_timeout() {
    local timeout_sec="$1"; shift
    local out
    out="$("$@" 2>&1 &
      bgpid=$!
      ( sleep "$timeout_sec" && kill -9 $bgpid 2>/dev/null ) &
      watcher=$!
      wait $bgpid 2>/dev/null
      rc=$?
      kill $watcher 2>/dev/null
      exit $rc
    )"
    local rc=$?
    printf '%s\n' "$out"
    return $rc
  }

  q1_out=""
  q2_out=""
  q1_rc=0
  q2_rc=0
  {
    echo "=== total customers (status != deleted) ==="
    q1_out="$(run_with_timeout 60 bash "$ssm_exec" "$q1")" || q1_rc=$?
    echo "$q1_out"
    echo "(q1 exit=$q1_rc)"
    echo ""
    echo "=== test-pattern customers ==="
    q2_out="$(run_with_timeout 60 bash "$ssm_exec" "$q2")" || q2_rc=$?
    echo "$q2_out"
    echo "(q2 exit=$q2_rc)"
  } > "$raw_file"

  # Only mark OK if both queries succeeded AND output contains digit (a count).
  if [ "$q1_rc" -eq 0 ] && [ "$q2_rc" -eq 0 ] && \
     echo "$q1_out" | grep -qE '[0-9]' && \
     echo "$q2_out" | grep -qE '[0-9]'; then
    add_row "staging_rds" "OK" "false" "staging RDS counts captured (see raw)" "staging_rds.txt"
  else
    add_row "staging_rds" "PROBE_ERROR" "false" "ssm_exec failed (q1_rc=$q1_rc, q2_rc=$q2_rc) — see raw" "staging_rds.txt"
  fi
fi

# ---------------------------------------------------------------------------
# 9. Privacy.com — list one card via API key
# ---------------------------------------------------------------------------

raw_file="$OUT/privacy_com.txt"
register_raw "privacy_com.txt"
if [ -z "${PRIVACY_PRODUCTION_API_KEY:-}" ]; then
  echo "SKIP_NO_CREDS: PRIVACY_PRODUCTION_API_KEY unset" > "$raw_file"
  add_row "privacy_com" "SKIP_NO_CREDS" "false" "Privacy.com API key not present" "privacy_com.txt"
else
  http_status="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 \
    -H "Authorization: api-key $PRIVACY_PRODUCTION_API_KEY" \
    "https://api.privacy.com/v1/cards?page_size=1" 2>&1 || echo "000")"
  {
    echo "endpoint=https://api.privacy.com/v1/cards?page_size=1"
    echo "http_status=$http_status"
    echo "(body NOT captured — Privacy.com responses contain cardholder PAN tails)"
  } > "$raw_file"
  if [ "$http_status" = "200" ]; then
    add_row "privacy_com" "OK" "false" "Privacy.com key authenticates" "privacy_com.txt"
  elif [ "$http_status" = "401" ]; then
    add_row "privacy_com" "ACTION_REQUIRED" "false" "Privacy.com key returned 401 — revoked?" "privacy_com.txt"
  else
    add_row "privacy_com" "PROBE_ERROR" "false" "Privacy.com returned HTTP $http_status" "privacy_com.txt"
  fi
fi

# ---------------------------------------------------------------------------
# 10. Footer
# ---------------------------------------------------------------------------

{
  echo "---"
  echo "Probe complete. Raw subfiles listed in manifest.txt."
  echo "Run: \`bash scripts/probe_live_state.sh\` again to refresh; new timestamp dir per run."
} >> "$SUMMARY"

echo "Probe complete: $OUT"
exit 0
