#!/usr/bin/env python3
"""Regenerate infra/api/tests/integration.rs from tests/integration/*.rs."""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_DIR = REPO_ROOT / "infra" / "api" / "tests"
INTEGRATION_DIR = TESTS_DIR / "integration"
INTEGRATION_ROOT = TESTS_DIR / "integration.rs"


def module_cfg(source_path: Path) -> str | None:
    text = source_path.read_text(encoding="utf-8")
    match = re.search(r"(?m)^#!\[(cfg\([^\]]+\))\]\s*$", text)
    if match:
        return match.group(1)
    return None


def render_root() -> str:
    files = sorted(INTEGRATION_DIR.glob("*.rs"), key=lambda p: p.stem)

    unconditional: list[str] = []
    conditional: dict[str, list[str]] = defaultdict(list)

    for file_path in files:
        module_name = file_path.stem
        cfg_expr = module_cfg(file_path)
        if cfg_expr is None:
            unconditional.append(module_name)
        else:
            conditional[cfg_expr].append(module_name)

    lines: list[str] = [
        "//! Generated by scripts/dev/regenerate_integration_test_root.py. Do not edit by hand.",
        "",
        "mod common;",
        "",
    ]

    for module_name in unconditional:
        lines.append(f"#[path = \"integration/{module_name}.rs\"]")
        lines.append(f"mod {module_name};")

    for cfg_expr in sorted(conditional):
        lines.append("")
        lines.append(f"#[{cfg_expr}]")
        for module_name in conditional[cfg_expr]:
            lines.append(f"#[path = \"integration/{module_name}.rs\"]")
            lines.append(f"mod {module_name};")

    lines.append("")
    return "\n".join(lines)


def cmd_print() -> int:
    sys.stdout.write(render_root())
    return 0


def cmd_write() -> int:
    INTEGRATION_ROOT.write_text(render_root(), encoding="utf-8")
    return 0


def cmd_check() -> int:
    expected = render_root()
    if not INTEGRATION_ROOT.exists():
        print(f"missing generated root: {INTEGRATION_ROOT}", file=sys.stderr)
        return 1
    actual = INTEGRATION_ROOT.read_text(encoding="utf-8")
    if actual != expected:
        print("integration.rs is stale; run --write", file=sys.stderr)
        return 1
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--print", dest="print_mode", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.write:
        return cmd_write()
    if args.check:
        return cmd_check()
    if args.print_mode:
        return cmd_print()
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
