#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/test_helpers.sh"

data_main_file="ops/terraform/data/main.tf"
data_vars_file="ops/terraform/data/variables.tf"
data_providers_file="ops/terraform/data/providers.tf"
data_outputs_file="ops/terraform/data/outputs.tf"
terraform_runbook_file="docs/runbooks/infra-terraform-apply.md"

assert_file_exists "$data_main_file" "data/main.tf exists"
assert_file_exists "$data_vars_file" "data/variables.tf exists"
assert_file_exists "$data_providers_file" "data/providers.tf exists"
assert_file_exists "$data_outputs_file" "data/outputs.tf exists"
assert_file_exists "$terraform_runbook_file" "Terraform apply runbook exists"

assert_contains_active "$data_vars_file" 'contains\(\["staging", "prod"\], var\.env\)' "Data module env variable restricts values to staging/prod"
assert_contains_active "$data_vars_file" '^[[:space:]]*variable[[:space:]]+"private_subnet_ids"' "Data module declares private_subnet_ids input"
assert_contains_active "$data_vars_file" '^[[:space:]]*variable[[:space:]]+"sg_rds_id"' "Data module declares sg_rds_id input"
assert_contains_active "$data_vars_file" '^[[:space:]]*variable[[:space:]]+"db_instance_class"' "Data module declares db_instance_class input"

assert_resource_count "$data_main_file" 14 "Stage 2 data module defines expected 14 Terraform resources"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_db_subnet_group"[[:space:]]+"main"' "RDS subnet group resource exists"
assert_contains_active "$data_main_file" '^[[:space:]]*subnet_ids[[:space:]]*=[[:space:]]*var\.private_subnet_ids' "RDS subnet group uses private subnet IDs"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"random_password"[[:space:]]+"db"' "random_password resource exists for DB password"
assert_contains_active "$data_main_file" '^[[:space:]]*length[[:space:]]*=[[:space:]]*32' "DB random password length is 32"
assert_contains_active "$data_main_file" '^[[:space:]]*special[[:space:]]*=[[:space:]]*false' "DB random password excludes special chars"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_db_instance"[[:space:]]+"main"' "RDS instance resource exists"
assert_contains_active "$data_main_file" '^[[:space:]]*engine_version[[:space:]]*=[[:space:]]*"17"' "RDS PostgreSQL engine version is 17"
assert_contains_active "$data_main_file" '^[[:space:]]*instance_class[[:space:]]*=[[:space:]]*var\.db_instance_class' "RDS instance class is parameterized"
assert_contains_active "$data_main_file" '^[[:space:]]*allocated_storage[[:space:]]*=[[:space:]]*20' "RDS allocated storage is 20 GB"
assert_contains_active "$data_main_file" '^[[:space:]]*max_allocated_storage[[:space:]]*=[[:space:]]*100' "RDS max allocated storage is 100 GB"
assert_contains_active "$data_main_file" '^[[:space:]]*storage_type[[:space:]]*=[[:space:]]*"gp3"' "RDS storage type is gp3"
assert_contains_active "$data_main_file" '^[[:space:]]*storage_encrypted[[:space:]]*=[[:space:]]*true' "RDS storage encryption is enabled"
assert_contains_active "$data_main_file" '^[[:space:]]*multi_az[[:space:]]*=[[:space:]]*local\.is_prod' "RDS Multi-AZ toggles by environment"
assert_contains_active "$data_main_file" '^[[:space:]]*backup_retention_period[[:space:]]*=[[:space:]]*30' "RDS backup retention is 30 days"
assert_contains_active "$data_main_file" '^[[:space:]]*backup_window[[:space:]]*=[[:space:]]*"02:00-03:00"' "RDS backup window is 02:00-03:00 UTC"
assert_contains_active "$data_main_file" '^[[:space:]]*deletion_protection[[:space:]]*=[[:space:]]*local\.is_prod' "RDS deletion protection toggles by environment"
assert_contains_active "$data_main_file" '^[[:space:]]*skip_final_snapshot[[:space:]]*=[[:space:]]*!local\.is_prod' "RDS final snapshot behavior toggles by environment"
assert_contains_active "$data_main_file" '^[[:space:]]*final_snapshot_identifier[[:space:]]*=[[:space:]]*local\.is_prod[[:space:]]*\?[[:space:]]*"fjcloud-\$\{var\.env\}-final"[[:space:]]*:[[:space:]]*null' "RDS prod final snapshot identifier follows naming convention"
assert_contains_active "$data_main_file" '^[[:space:]]*db_subnet_group_name[[:space:]]*=[[:space:]]*aws_db_subnet_group\.main\.name' "RDS instance uses DB subnet group"
assert_contains_active "$data_main_file" '^[[:space:]]*vpc_security_group_ids[[:space:]]*=[[:space:]]*\[var\.sg_rds_id\]' "RDS instance uses sg_rds_id input"
assert_contains_active "$data_main_file" '^[[:space:]]*publicly_accessible[[:space:]]*=[[:space:]]*false' "RDS instance is not publicly accessible"
assert_contains_active "$data_main_file" '^[[:space:]]*performance_insights_enabled[[:space:]]*=[[:space:]]*true' "RDS performance insights are enabled"
assert_contains_active "$data_main_file" '^[[:space:]]*enabled_cloudwatch_logs_exports[[:space:]]*=[[:space:]]*\["postgresql"\]' "RDS exports PostgreSQL logs to CloudWatch"
assert_contains_active "$data_main_file" '^[[:space:]]*rds_postgresql_log_retention_days[[:space:]]*=[[:space:]]*30' "RDS PostgreSQL log retention default is 30 days in locals"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_cloudwatch_log_group"[[:space:]]+"rds_postgresql"' "CloudWatch log group resource exists for RDS PostgreSQL logs"
assert_contains_active "$data_main_file" '^[[:space:]]*name[[:space:]]*=[[:space:]]*"/aws/rds/instance/\$\{aws_db_instance\.main\.identifier\}/postgresql"' "RDS PostgreSQL log group name derives from DB identifier"
assert_contains_active "$data_main_file" '^[[:space:]]*retention_in_days[[:space:]]*=[[:space:]]*local\.rds_postgresql_log_retention_days' "RDS PostgreSQL log retention uses local default"
assert_not_contains_active "$data_main_file" '^[[:space:]]*password[[:space:]]*=[[:space:]]*"[^"]+"' "RDS password is not hardcoded as a string literal"

assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_ssm_parameter"[[:space:]]+"db_password"' "SSM parameter resource exists for db_password"
assert_contains_active "$data_main_file" '^[[:space:]]*name[[:space:]]*=[[:space:]]*"/fjcloud/\$\{var\.env\}/db_password"' "DB password SSM parameter path is correct"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_ssm_parameter"[[:space:]]+"database_url"' "SSM parameter resource exists for database_url"
assert_contains_active "$data_main_file" '^[[:space:]]*name[[:space:]]*=[[:space:]]*"/fjcloud/\$\{var\.env\}/database_url"' "Database URL SSM parameter path is correct"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"random_password"[[:space:]]+"internal_auth_token"' "random_password resource exists for internal auth token"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_ssm_parameter"[[:space:]]+"internal_auth_token"' "SSM parameter resource exists for internal_auth_token"
assert_contains_active "$data_main_file" '^[[:space:]]*name[[:space:]]*=[[:space:]]*"/fjcloud/\$\{var\.env\}/internal_auth_token"' "internal_auth_token SSM parameter path is correct"
assert_contains_active "$data_main_file" 'random_password\.internal_auth_token\.result' "internal_auth_token uses generated secret material"
assert_contains_active "$data_main_file" '^[[:space:]]*type[[:space:]]*=[[:space:]]*"SecureString"' "Sensitive SSM parameters use SecureString"
assert_contains_active "$data_main_file" 'random_password\.db\.result' "Database URL uses generated DB password"
assert_contains_active "$data_main_file" 'aws_db_instance\.main\.endpoint' "Database URL uses provisioned RDS endpoint"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_s3_bucket"[[:space:]]+"cold"' "S3 cold bucket resource exists"
assert_contains_active "$data_main_file" '^[[:space:]]*bucket[[:space:]]*=[[:space:]]*"fjcloud-cold-\$\{var\.env\}"' "S3 cold bucket naming matches convention"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_s3_bucket_versioning"[[:space:]]+"cold"' "S3 bucket versioning resource exists"
assert_contains_active "$data_main_file" '^[[:space:]]*status[[:space:]]*=[[:space:]]*"Enabled"' "S3 bucket versioning is enabled"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_s3_bucket_server_side_encryption_configuration"[[:space:]]+"cold"' "S3 bucket encryption configuration resource exists"
assert_contains_active "$data_main_file" '^[[:space:]]*sse_algorithm[[:space:]]*=[[:space:]]*"AES256"' "S3 bucket uses SSE-S3 (AES256)"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_s3_bucket_public_access_block"[[:space:]]+"cold"' "S3 public access block resource exists"
assert_contains_active "$data_main_file" '^[[:space:]]*block_public_acls[[:space:]]*=[[:space:]]*true' "S3 blocks public ACLs"
assert_contains_active "$data_main_file" '^[[:space:]]*block_public_policy[[:space:]]*=[[:space:]]*true' "S3 blocks public policies"
assert_contains_active "$data_main_file" '^[[:space:]]*ignore_public_acls[[:space:]]*=[[:space:]]*true' "S3 ignores public ACLs"
assert_contains_active "$data_main_file" '^[[:space:]]*restrict_public_buckets[[:space:]]*=[[:space:]]*true' "S3 restricts public buckets"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_s3_bucket_lifecycle_configuration"[[:space:]]+"cold"' "S3 lifecycle configuration resource exists"
assert_contains_active "$data_main_file" '^[[:space:]]*filter[[:space:]]*\{\}' "S3 lifecycle rule has explicit empty filter block"
assert_contains_active "$data_main_file" '^[[:space:]]*days[[:space:]]*=[[:space:]]*90' "S3 lifecycle transition threshold is 90 days"
assert_contains_active "$data_main_file" '^[[:space:]]*storage_class[[:space:]]*=[[:space:]]*"GLACIER_IR"' "S3 lifecycle transitions to Glacier Instant Retrieval"
assert_contains_active "$data_main_file" '^[[:space:]]*resource[[:space:]]+"aws_ssm_parameter"[[:space:]]+"cold_bucket_name"' "SSM parameter resource exists for cold bucket name"
assert_contains_active "$data_main_file" '^[[:space:]]*name[[:space:]]*=[[:space:]]*"/fjcloud/\$\{var\.env\}/cold_bucket_name"' "Cold bucket name SSM parameter path is correct"

assert_contains_active "$data_outputs_file" '^[[:space:]]*output[[:space:]]+"db_endpoint"' "Data outputs include db_endpoint"
assert_contains_active "$data_outputs_file" '^[[:space:]]*output[[:space:]]+"db_name"' "Data outputs include db_name"
assert_contains_active "$data_outputs_file" '^[[:space:]]*output[[:space:]]+"cold_bucket_name"' "Data outputs include cold_bucket_name"
assert_contains_active "$data_outputs_file" '^[[:space:]]*output[[:space:]]+"cold_bucket_arn"' "Data outputs include cold_bucket_arn"
assert_contains_active "$data_outputs_file" '^[[:space:]]*output[[:space:]]+"db_password_ssm_arn"' "Data outputs include db_password_ssm_arn"
assert_contains_active "$data_outputs_file" '^[[:space:]]*output[[:space:]]+"database_url_ssm_arn"' "Data outputs include database_url_ssm_arn"

assert_contains_active "$terraform_runbook_file" 'terraform import' "Terraform apply runbook documents terraform import"
assert_contains_active "$terraform_runbook_file" 'module\.data\.aws_cloudwatch_log_group\.rds_postgresql' "Terraform apply runbook references RDS PostgreSQL log group resource address"
assert_contains_active "$terraform_runbook_file" '/aws/rds/instance/fjcloud-<env>/postgresql' "Terraform apply runbook documents RDS PostgreSQL log group naming shape"

test_summary "Stage 2 static checks"
